{
 "title": "MySQLRouter Exporter",
 "description": "https://github.com/rluisr/mysqlrouter_exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(mysqlrouter_router_status,service)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(mysqlrouter_router_status{service=\"$service\"},hostname)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mysqlrouter_metadata{name=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table-old",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysqlrouter_router_status{hostname=\"$host\"}"
    }
   ]
  },
  {
   "title": "Nodes of cluster",
   "type": "stat",
   "description": "Nodes of cluster",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysqlrouter_metadata_config_nodes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$host - Route Blocked Hosts",
   "type": "bargauge",
   "description": "Each routing has its own list of blocked hosts. Blocked clients receive the MySQL Server error 1129 code with a slightly different error message: \"1129: Too many connection errors from fail.example.com\". The Router logs contain extra information for blocked clients, such as: INFO [...] 1 authentication errors for fail.example.com (max 100) WARNING [...] blocking client host fail.example.com",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysqlrouter_route_blocked_hosts{name=~\"$cluster.*\", router_hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$host - Route Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysqlrouter_route_health{router_hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$host - Route Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysqlrouter_route_active_connections{name=~\"$cluster.*\", router_hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$host - Route Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysqlrouter_route_total_connections{name=~\"$cluster.*\", router_hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$host - All Connections Information",
   "type": "table",
   "description": "Click table column",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "mysqlrouter_route_connections_byte_to_server{router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_byte_from_server{router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_time_connected_to_server{router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_time_last_received_from_server{router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_time_last_sent_to_server{router_hostname=\"$host\"}"
    },
    {
     "expr": "mysqlrouter_route_connections_time_started{router_hostname=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - Route byte from/to server",
   "type": "timeseries",
   "description": "If route have no connections, There is no data.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mysqlrouter_route_connections_byte_from_server{router_hostname=\"$host\"}",
     "legendFormat": "from_server {{name}} - {{source_address}} -> {{destination_address}}"
    },
    {
     "expr": "mysqlrouter_route_connections_byte_to_server{outer_hostname=\"$host\"}",
     "legendFormat": "to_server {{name}} - {{destination_address}} -> {{source_address}}"
    }
   ]
  }
 ]
}