# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

import logging

import jubilant_backports
import pytest
import tenacity

from . import architecture
from .helpers import (
    APPLICATION_DEFAULT_APP_NAME,
    MYSQL_DEFAULT_APP_NAME,
    MYSQL_ROUTER_DEFAULT_APP_NAME,
    get_tls_certificate_issuer,
)

logger = logging.getLogger(__name__)

MYSQL_APP_NAME = MYSQL_DEFAULT_APP_NAME
MYSQL_ROUTER_APP_NAME = MYSQL_ROUTER_DEFAULT_APP_NAME
TEST_APP_NAME = APPLICATION_DEFAULT_APP_NAME
SLOW_TIMEOUT = 15 * 60
RETRY_TIMEOUT = 60

TLS_APP_NAME = "self-signed-certificates"
TLS_CHANNEL = "1/stable"
TLS_CONFIG = {"ca-common-name": "Test CA"}
TLS_BASE = "ubuntu@24.04"


@pytest.mark.abort_on_fail
def test_build_deploy_and_relate(juju: jubilant_backports.Juju, charm, ubuntu_base) -> None:
    """Test encryption when backend database is using TLS."""
    logger.info("Deploy and relate all applications")
    # deploy mysql first
    juju.deploy(
        MYSQL_APP_NAME,
        channel="8.0/edge",
        app=MYSQL_APP_NAME,
        config={"profile": "testing"},
        num_units=1,
        constraints={"arch": architecture.architecture},
    )

    # tls, test app and router
    juju.deploy(
        charm,
        app=MYSQL_ROUTER_APP_NAME,
        base=ubuntu_base,
    )
    juju.deploy(
        TLS_APP_NAME,
        app=TLS_APP_NAME,
        channel=TLS_CHANNEL,
        config=TLS_CONFIG,
        base=TLS_BASE,
    )
    juju.deploy(
        TEST_APP_NAME,
        app=TEST_APP_NAME,
        channel="latest/edge",
        base=ubuntu_base,
        config={"sleep_interval": 1000},
    )

    juju.integrate(f"{MYSQL_ROUTER_APP_NAME}:backend-database", f"{MYSQL_APP_NAME}:database")
    juju.integrate(f"{TEST_APP_NAME}:database", f"{MYSQL_ROUTER_APP_NAME}:database")

    logger.info("Waiting for applications to become active")
    # We can safely wait only for test application to be ready, given that it will
    # only become active once all the other applications are ready.
    juju.wait(
        ready=lambda status: status.apps[TEST_APP_NAME].app_status.current == "active",
        timeout=SLOW_TIMEOUT,
    )


@pytest.mark.abort_on_fail
def test_connected_encryption(juju: jubilant_backports.Juju) -> None:
    """Test encryption when backend database is using TLS."""
    mysqlrouter_unit_name = f"{MYSQL_ROUTER_APP_NAME}/0"

    for attempt in tenacity.Retrying(
        reraise=True,
        stop=tenacity.stop_after_delay(RETRY_TIMEOUT),
        wait=tenacity.wait_fixed(10),
    ):
        with attempt:
            issuer = get_tls_certificate_issuer(
                juju,
                mysqlrouter_unit_name,
                socket="/var/snap/charmed-mysql/common/run/mysqlrouter/mysql.sock",
            )
            assert "Issuer: CN = MySQL_Router_Auto_Generated_CA_Certificate" in issuer, (
                "Expected mysqlrouter autogenerated certificate"
            )

    logger.info("Relating TLS with mysqlrouter")
    juju.integrate(TLS_APP_NAME, MYSQL_ROUTER_APP_NAME)

    logger.info("Getting certificate issuer after relating with tls operator")
    for attempt in tenacity.Retrying(
        reraise=True,
        stop=tenacity.stop_after_delay(RETRY_TIMEOUT),
        wait=tenacity.wait_fixed(10),
    ):
        with attempt:
            issuer = get_tls_certificate_issuer(
                juju,
                mysqlrouter_unit_name,
                socket="/var/snap/charmed-mysql/common/run/mysqlrouter/mysql.sock",
            )
            assert "CN = Test CA" in issuer, (
                f"Expected mysqlrouter certificate from {TLS_APP_NAME}"
            )

    logger.info("Removing relation TLS with mysqlrouter")
    juju.remove_relation(
        f"{TLS_APP_NAME}:certificates",
        f"{MYSQL_ROUTER_APP_NAME}:certificates",
    )

    for attempt in tenacity.Retrying(
        reraise=True,
        stop=tenacity.stop_after_delay(RETRY_TIMEOUT),
        wait=tenacity.wait_fixed(10),
    ):
        with attempt:
            issuer = get_tls_certificate_issuer(
                juju,
                mysqlrouter_unit_name,
                socket="/var/snap/charmed-mysql/common/run/mysqlrouter/mysql.sock",
            )
            assert "Issuer: CN = MySQL_Router_Auto_Generated_CA_Certificate" in issuer, (
                "Expected mysqlrouter autogenerated CA certificate"
            )
