# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

import logging

import jubilant_backports
import pytest
import tenacity

from . import architecture
from .helpers import (
    MYSQL_DEFAULT_APP_NAME,
    MYSQL_ROUTER_DEFAULT_APP_NAME,
    execute_queries_against_unit,
    get_data_integrator_credentials,
    get_tls_certificate_issuer,
)

logger = logging.getLogger(__name__)

MYSQL_APP_NAME = MYSQL_DEFAULT_APP_NAME
MYSQL_ROUTER_APP_NAME = MYSQL_ROUTER_DEFAULT_APP_NAME
DATA_INTEGRATOR_APP_NAME = "data-integrator"
SLOW_TIMEOUT = 15 * 60
RETRY_TIMEOUT = 60
TEST_DATABASE = "testdatabase"
TEST_TABLE = "testtable"

# Juju 3+ configuration for TLS
tls_app_name = "self-signed-certificates"
tls_channel = "1/stable"
tls_config = {"ca-common-name": "Test CA"}
tls_base = "ubuntu@24.04"


@pytest.mark.abort_on_fail
def test_external_connectivity_with_data_integrator(
    juju: jubilant_backports.Juju, charm, ubuntu_base
) -> None:
    """Test encryption when backend database is using TLS."""
    logger.info("Deploy and relate all applications")
    # deploy mysql first
    juju.deploy(
        MYSQL_APP_NAME,
        channel="8.0/edge",
        config={"profile": "testing"},
        num_units=1,
        constraints={"arch": architecture.architecture},
    )
    data_integrator_config = {"database-name": TEST_DATABASE}

    # tls, data-integrator and router
    juju.deploy(
        charm,
        app=MYSQL_ROUTER_APP_NAME,
        base=ubuntu_base,
    )
    juju.deploy(
        tls_app_name,
        app=tls_app_name,
        channel=tls_channel,
        config=tls_config,
        base=tls_base,
    )
    juju.deploy(
        DATA_INTEGRATOR_APP_NAME,
        app=DATA_INTEGRATOR_APP_NAME,
        channel="latest/stable",
        base=ubuntu_base,
        config=data_integrator_config,
    )

    juju.integrate(f"{MYSQL_ROUTER_APP_NAME}:backend-database", f"{MYSQL_APP_NAME}:database")
    juju.integrate(f"{DATA_INTEGRATOR_APP_NAME}:mysql", f"{MYSQL_ROUTER_APP_NAME}:database")

    logger.info("Waiting for applications to become active")
    # We can safely wait only for data-integrator to be ready,
    # given that it will only become active once all the other
    # applications are ready.
    juju.wait(
        ready=lambda status: status.apps[DATA_INTEGRATOR_APP_NAME].app_status == "active",
        timeout=SLOW_TIMEOUT,
    )

    credentials = get_data_integrator_credentials(juju, DATA_INTEGRATOR_APP_NAME)
    databases = execute_queries_against_unit(
        credentials["endpoints"].split(",")[0].split(":")[0],
        credentials["username"],
        credentials["password"],
        ["SHOW DATABASES;"],
        port=credentials["endpoints"].split(",")[0].split(":")[1],
    )
    assert TEST_DATABASE in databases


@pytest.mark.abort_on_fail
def test_external_connectivity_with_data_integrator_and_tls(juju: jubilant_backports.Juju) -> None:
    """Test data integrator along with TLS operator"""
    logger.info("Ensuring no data exists in the test database")

    credentials = get_data_integrator_credentials(juju, DATA_INTEGRATOR_APP_NAME)
    [database_host, database_port] = credentials["endpoints"].split(",")[0].split(":")
    mysqlrouter_unit = f"{MYSQL_ROUTER_APP_NAME}/0"

    show_tables_sql = [
        f"SHOW TABLES IN {TEST_DATABASE};",
    ]
    tables = execute_queries_against_unit(
        database_host,
        credentials["username"],
        credentials["password"],
        show_tables_sql,
        port=database_port,
    )
    assert len(tables) == 0, f"Unexpected tables in the {TEST_DATABASE} database"

    issuer = get_tls_certificate_issuer(
        juju,
        mysqlrouter_unit,
        host=database_host,
        port=database_port,
    )
    assert "Issuer: CN = MySQL_Router_Auto_Generated_CA_Certificate" in issuer, (
        "Expected mysqlrouter autogenerated certificate"
    )

    logger.info(f"Relating mysqlrouter with {tls_app_name}")
    juju.integrate(f"{MYSQL_ROUTER_APP_NAME}:certificates", f"{tls_app_name}:certificates")

    for attempt in tenacity.Retrying(
        reraise=True,
        stop=tenacity.stop_after_delay(RETRY_TIMEOUT),
        wait=tenacity.wait_fixed(10),
    ):
        with attempt:
            issuer = get_tls_certificate_issuer(
                juju,
                mysqlrouter_unit,
                host=database_host,
                port=database_port,
            )
            assert "CN = Test CA" in issuer, (
                f"Expected mysqlrouter certificate from {tls_app_name}"
            )

    create_table_and_insert_data_sql = [
        f"CREATE TABLE {TEST_DATABASE}.{TEST_TABLE} (id int, primary key(id));",
        f"INSERT INTO {TEST_DATABASE}.{TEST_TABLE} VALUES (1), (2);",
    ]
    execute_queries_against_unit(
        database_host,
        credentials["username"],
        credentials["password"],
        create_table_and_insert_data_sql,
        port=database_port,
        commit=True,
    )

    select_data_sql = [
        f"SELECT * FROM {TEST_DATABASE}.{TEST_TABLE};",
    ]
    data = execute_queries_against_unit(
        database_host,
        credentials["username"],
        credentials["password"],
        select_data_sql,
        port=database_port,
    )
    assert data == [1, 2], f"Unexpected data in table {TEST_DATABASE}.{TEST_TABLE}"

    logger.info(f"Removing relation between mysqlrouter and {tls_app_name}")
    juju.remove_relation(f"{MYSQL_ROUTER_APP_NAME}:certificates", f"{tls_app_name}:certificates")

    for attempt in tenacity.Retrying(
        reraise=True,
        stop=tenacity.stop_after_delay(RETRY_TIMEOUT),
        wait=tenacity.wait_fixed(10),
    ):
        with attempt:
            issuer = get_tls_certificate_issuer(
                juju,
                mysqlrouter_unit,
                host=database_host,
                port=database_port,
            )
            assert "Issuer: CN = MySQL_Router_Auto_Generated_CA_Certificate" in issuer, (
                "Expected mysqlrouter autogenerated certificate"
            )

    select_data_sql = [
        f"SELECT * FROM {TEST_DATABASE}.{TEST_TABLE};",
    ]
    data = execute_queries_against_unit(
        database_host,
        credentials["username"],
        credentials["password"],
        select_data_sql,
        port=database_port,
    )
    assert data == [1, 2], f"Unexpected data in table {TEST_DATABASE}.{TEST_TABLE}"
