# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

import logging
from pathlib import Path

import jubilant_backports
import pytest
import tenacity
import yaml

from . import architecture
from .helpers import (
    APPLICATION_DEFAULT_APP_NAME,
    MYSQL_DEFAULT_APP_NAME,
    MYSQL_ROUTER_DEFAULT_APP_NAME,
    get_tls_certificate_issuer,
    wait_for_apps_status,
)

logger = logging.getLogger(__name__)

METADATA = yaml.safe_load(Path("./metadata.yaml").read_text())

MYSQL_APP_NAME = MYSQL_DEFAULT_APP_NAME
MYSQL_ROUTER_APP_NAME = MYSQL_ROUTER_DEFAULT_APP_NAME
TEST_APP_NAME = APPLICATION_DEFAULT_APP_NAME
SLOW_TIMEOUT = 15 * 60
RETRY_TIMEOUT = 2 * 60

# Juju 3+ configuration for TLS
tls_app_name = "self-signed-certificates"
tls_channel = "1/stable"
tls_config = {"ca-common-name": "Test CA"}
tls_base = "ubuntu@24.04"


@pytest.mark.abort_on_fail
def test_deploy_and_relate(juju: jubilant_backports.Juju, charm, ubuntu_base) -> None:
    """Test encryption when backend database is using TLS."""
    mysqlrouter_resources = {
        "mysql-router-image": METADATA["resources"]["mysql-router-image"]["upstream-source"]
    }

    logger.info("Deploy and relate all applications")
    # deploy mysql first
    juju.deploy(
        MYSQL_APP_NAME,
        channel="8.0/edge",
        app=MYSQL_APP_NAME,
        config={"profile": "testing"},
        base=ubuntu_base,
        num_units=1,
        trust=True,
        constraints={"arch": architecture.architecture},
    )

    # tls, test app and router
    juju.deploy(
        charm,
        app=MYSQL_ROUTER_APP_NAME,
        resources=mysqlrouter_resources,
        base=ubuntu_base,
        num_units=1,
        trust=True,
    )
    juju.deploy(
        tls_app_name,
        app=tls_app_name,
        channel=tls_channel,
        config=tls_config,
        base=tls_base,
        constraints={"arch": architecture.architecture},
    )
    juju.deploy(
        TEST_APP_NAME,
        app=TEST_APP_NAME,
        channel="latest/edge",
        base=ubuntu_base,
        constraints={"arch": architecture.architecture},
    )

    juju.integrate(f"{MYSQL_ROUTER_APP_NAME}:backend-database", f"{MYSQL_APP_NAME}:database")
    juju.integrate(f"{TEST_APP_NAME}:database", f"{MYSQL_ROUTER_APP_NAME}:database")

    logger.info("Waiting for applications to become active")
    # We can safely wait only for test application to be ready, given that it will
    # only become active once all the other applications are ready.
    juju.wait(
        ready=wait_for_apps_status(jubilant_backports.all_active, TEST_APP_NAME),
        timeout=SLOW_TIMEOUT,
    )


@pytest.mark.abort_on_fail
def test_connected_encryption(juju: jubilant_backports.Juju) -> None:
    """Test encryption when backend database is using TLS."""
    mysqlrouter_unit = f"{MYSQL_ROUTER_APP_NAME}/0"

    for attempt in tenacity.Retrying(
        reraise=True,
        stop=tenacity.stop_after_delay(RETRY_TIMEOUT),
        wait=tenacity.wait_fixed(10),
    ):
        with attempt:
            issuer = get_tls_certificate_issuer(
                juju,
                mysqlrouter_unit,
                host="127.0.0.1",
                port=6446,
            )
            assert "Issuer: CN = MySQL_Router_Auto_Generated_CA_Certificate" in issuer, (
                "Expected mysqlrouter autogenerated certificate"
            )

    logger.info("Relating TLS with mysqlrouter")
    juju.integrate(tls_app_name, MYSQL_ROUTER_APP_NAME)

    logger.info("Getting certificate issuer after relating with tls operator")
    for attempt in tenacity.Retrying(
        reraise=True,
        stop=tenacity.stop_after_delay(RETRY_TIMEOUT),
        wait=tenacity.wait_fixed(10),
    ):
        with attempt:
            issuer = get_tls_certificate_issuer(
                juju,
                mysqlrouter_unit,
                host="127.0.0.1",
                port=6446,
            )
            assert "CN = Test CA" in issuer, (
                f"Expected mysqlrouter certificate from {tls_app_name}"
            )

    logger.info("Removing relation TLS with mysqlrouter")
    juju.remove_relation(
        f"{tls_app_name}:certificates",
        f"{MYSQL_ROUTER_APP_NAME}:certificates",
    )

    for attempt in tenacity.Retrying(
        reraise=True,
        stop=tenacity.stop_after_delay(RETRY_TIMEOUT),
        wait=tenacity.wait_fixed(10),
    ):
        with attempt:
            issuer = get_tls_certificate_issuer(
                juju,
                mysqlrouter_unit,
                host="127.0.0.1",
                port=6446,
            )
            assert "Issuer: CN = MySQL_Router_Auto_Generated_CA_Certificate" in issuer, (
                "Expected mysqlrouter autogenerated CA certificate"
            )
