# https://canonical-charm-refresh.readthedocs-hosted.com/latest/refresh-versions-toml/

charm_major = 1
workload = "8.0.45"

[snap]
name = "charmed-mysql"

[snap.revisions]
# amd64
x86_64 = "215"
# arm64
aarch64 = "213"
# s390x
s390x = "214"
