# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitattributes'
      - '.github/renovate.json5'

jobs:
  lint-workflows:
    name: Lint workflows
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v50
    permissions:
      contents: read

  lint:
    strategy:
      matrix:
        path:
          - kubernetes
          - machines
    name: Lint | ${{ matrix.path }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install terraform
        run: |
          sudo snap install terraform --classic
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run linters
        working-directory: ${{ matrix.path }}
        run: |
          tox run -e lint
          tox run -e lint-terraform

  unit-test:
    strategy:
      matrix:
        path:
          - kubernetes
          - machines
    name: Unit test | ${{ matrix.path }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run tests
        working-directory: ${{ matrix.path }}
        run: tox run -e unit

  build:
    strategy:
      matrix:
        path:
          - kubernetes
          - machines
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v50
    with:
      path-to-charm-directory: ${{ matrix.path }}
    permissions:
      actions: read
      contents: read

  integration-test:
    name: Integration tests
    needs:
      - lint-workflows
      - lint
      - unit-test
      - build
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.path }}
    secrets:
      UBUNTU_PRO_TOKEN: ${{ secrets.UBUNTU_PRO_TOKEN }}
      LANDSCAPE_ACCOUNT_NAME: ${{ secrets.LANDSCAPE_ACCOUNT_NAME }}
      LANDSCAPE_REGISTRATION_KEY: ${{ secrets.LANDSCAPE_REGISTRATION_KEY }}
    permissions:
      actions: read
