# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub edge

on:
  push:
    branches:
      - '8.4/edge'
    paths-ignore:
      - 'docs/**'
      - '.gitattributes'
      - '.github/renovate.json5'

jobs:
  tag:
    name: Create charm refresh compatibility version git tag
    uses: canonical/data-platform-workflows/.github/workflows/tag_charm_edge.yaml@v49
    with:
      track: '8.4'
    permissions:
      actions: read
      contents: write  # Needed to create git tag

  build:
    name: Build charm | ${{ matrix.path }}
    needs:
      - tag
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v49
    with:
      cache: false  # TODO: revert when PR merged + charmcraft-hub cache built
      path-to-charm-directory: ${{ matrix.path }}
    permissions:
      actions: read
      contents: read

  integration-test:
    name: Integration tests
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.path }}
    secrets:
      UBUNTU_PRO_TOKEN: ${{ secrets.UBUNTU_PRO_TOKEN }}
      LANDSCAPE_ACCOUNT_NAME: ${{ secrets.LANDSCAPE_ACCOUNT_NAME }}
      LANDSCAPE_REGISTRATION_KEY: ${{ secrets.LANDSCAPE_REGISTRATION_KEY }}
    permissions:
      actions: read

  release:
    strategy:
      matrix:
        path:
          - kubernetes
          - machines
    name: Release charm | ${{ matrix.path }}
    needs:
      - build
      - integration-test
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v49
    with:
      track: '8.4'
      path-to-charm-directory: ${{ matrix.path }}
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      actions: read    # Needed for GitHub API call to get workflow version
      contents: write  # Needed to create git tags
