# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

# Usage documentation: static-code-analysis.md

name: TICS run self-hosted test (github-action)

on:
  schedule:
    - cron: "0 2 * * 6" # Every Saturday 2:00 AM UTC
  workflow_dispatch:
    inputs:
      operator:
        description: 'Operator directory to scan'
        required: true
        default: 'mysql-router-k8s'
      ref:
        description: 'Git ref to checkout'
        required: false

jobs:
  tiobe-scan:
    name: Tiobe scan
    runs-on: [self-hosted, tiobe]
    timeout-minutes: 60
    permissions: {}
    steps:
      - name: Checkout the project
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          sparse-checkout: |
            ${{ inputs.operator }}
            common
          ref: ${{ inputs.ref }}

      - name: Create and activate virtual environment
        run: |
          sudo apt update && sudo apt install -y python3-venv
          python3 -m venv .venv
          . .venv/bin/activate
          pip install flake8 poetry pylint pytest tox
          echo PATH="$PATH" >> "$GITHUB_ENV"

      - name: Install project dependencies
        env:
          OPERATOR: ${{ inputs.operator }}
        run: |
          . .venv/bin/activate
          cd "$OPERATOR"
          poetry install --only main,charm-libs

      - name: Run coverage tests
        env:
          OPERATOR: ${{ inputs.operator }}
        run: |
          tox -e unit -c "$OPERATOR/tox.ini"

      - name: Coverage reports for TICS
        env:
          OPERATOR: ${{ inputs.operator }}
        run: |
          mkdir -p "$OPERATOR/.cover"
          cp "$OPERATOR/coverage.xml" "$OPERATOR/.cover/cobertura.xml"
          # Common module coverage report.
          mkdir -p common/.cover
          cp common/coverage.xml common/.cover/cobertura.xml

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v4
        with:
          mode: qserver
          project: mysql-router-operators
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true